### PR TITLE
Processed Friso feedback, fixes #108

### LINKED ISSUE #108: Add the feedback of Friso to the final report

### PR DESCRIPTION
**Pull request by jwgmeligmeyling**
We still have to run the spell checker and possibly add some images.

### CODE REVIEW

**Comment by eanker** [comment]
We haven't added image, do want them and where?

**Comment by jwgmeligmeyling** [comment]
I think this is good, but I think this is very general. We might just want to add some images to the interaction design section or at the introduction. And the Rtree #103 chapter can be visualised with an image.

See: #112

**Comment by TimvdLippe** [comment]
Can be merged as is, so we open new PRs for the other issues?

**Comment by GijsWeterings** [comment]
LGTM, can be merged

**Pull request merged**
