### PR TITLE
Final report merge branch

### PR DESCRIPTION
**Pull request by jwgmeligmeyling**

### CODE REVIEW

**Comment by jwgmeligmeyling** [comment]
> Our clients from the business world want this product to be developed.

Komt een beetje uit de lucht vallen.

**Comment by jwgmeligmeyling** [comment]
> MoodCat**.** After that we

**Comment by jwgmeligmeyling** [comment]
> to music together It combines enjoying**.**

**Comment by TimvdLippe** [comment]
Checks okay. Can be merged =]

**Pull request merged**
