### PR TITLE
Sprint Reflection 4

### PR DESCRIPTION
**Pull request by jwgmeligmeyling**

### CODE REVIEW

**Comment by GijsWeterings** [comment]
#84-core: we said we pushed this to next week, but it's not in the sprint plan due to the midterms

**Comment by TimvdLippe** [comment]
Apart from the header on the 3rd page, it looks good. Especially the formatting is improved.

**Comment by eanker** [comment]
This document was a team effort and so I agree with this document.
After fixing the error Gijs mentoined I would say, merge it.

**Comment by jwgmeligmeyling** [comment]
This is ok! :+1:

**Pull request merged**
